### ISSUE TITLE
Annotation types cannot be signed literals

### ISSUE THREAD

**Issue by Hdt80bro** [FAForever/fa-lua-vscode-extension#10]
The annotation type system is fully equipped to use literals as types--except if they're signed numbers.
![image](https://user-images.githubusercontent.com/37224614/178421723-8446d237-91ef-449a-bacc-54466f4b6b78.png)
(Yes, those errors are all the same)

**Comment by hahn-kev** [comment]
actually most of these are the same as the negative enum issue I believe, should be fixed when I merge that in. Just waiting for that version to be released before I merge it in.

**Comment by hahn-kev** [comment]
Should be fixed now
