### ISSUE TITLE
Blueprint files (`.bp`) should have syntax highlighting, but not hog up the extension

### ISSUE THREAD

**Issue by Garanas** [FAForever/fa-lua-vscode-extension#8]
I've associated `.bp` files as `.lua` files as they are essentially one large Lua table with a global call around it. The global call is used by `blueprints.lua` to understand where it should register the blueprint.

When I did this the extension suddenly had to take into account a whole lot more files, even though the blueprint files do not really add to the intellisense part of the extension. I just want to syntax highlight them.

**Comment by hahn-kev** [comment]
Should be resolved with https://github.com/FAForever/fa/pull/3887
